### ISSUE TITLE
autocomplete bug numbers in magit commit messages

### ISSUE THREAD

**Issue by fommil** [arnested/bug-reference-github#2]
it would be incredibly useful to be able to reference github issues from the magit commit message mode.

e.g. imagine typing

```
improves speed according to #3
```

and then have it expanded into 10 tickets that start with `3`, then as the user types more the list is filtered. i.e. exactly the way it works when in github and you type `#` and it completes.

It would be great if there was a way to search the ticket names. Some keybinding that changes to use the github ticket search api to find the ticket and insert the number (optionally the name as well).

**Comment by arnested** [comment]
I like the idea.

But as far as I can see the Github API doesn't let you do searches on the issue number. And doing a full list of issue numbers and filtering it down in elisp would not scale well on large repositories (i.e. Homebrew has 40000+ issues).

Although I like the idea I think it might be out of scope for this project though.

**Comment by fommil** [comment]
https://developer.github.com/v3/search/#search-issues

**Comment by arnested** [comment]
This should be possible with the [git-commit-insert-issue](https://gitlab.com/emacs-stuff/git-commit-insert-issue) pacage so I'm going to close this issue.

**Comment by fommil** [comment]
Nice!
