### ISSUE TITLE
Presence of dir file, but not info file, in repository, causes confusion for MELPA users

### ISSUE THREAD

**Issue by aplaice** [arnested/bug-reference-github#3]
## In brief

Would you consider including the generated info file directly in the repository, so that it can be pulled and included by MELPA?

## In detail

The generation of the info manual from the README, as specified in the Makefile, is a really great idea.

Unfortunately, the MELPA packaging scripts do not (by design) execute the Makefile and so do not generate the info file from the `README.md`. (As far as I know, the only files that MELPA does generate, while creating a package, are an info file from Texinfo (texi) and a dir file, if necessary. It doesn't support other conversions to avoid complexity and arbitrary code execution.) However, MELPA does automatically pull the `dir` file from the repository, making it incorrectly appear as if a manual was present. [See here](https://github.com/melpa/melpa/issues/4948) for more details.

Looking at the Marmalade package of `bug-reference-github`, it does not seem to contain a generated info file, either.

Hence, including the generated info file directly in the repository, would be helpful.

To avoid having to do this manually, you could use a pre-commit hook, like for example in [writeroom-mode](https://github.com/joostkremers/writeroom-mode/blob/master/precommit.sh). The generated info file does not necessarily have to be in the root directory — its location can be specified by the MELPA recipe.

Alternatively, the `dir` file could be manually excluded from MELPA or the `master` branch used instead of the `develop` one.

Thank you for a very useful and popular emacs package!

**Comment by arnested** [comment]
A very good idea. I have wanted to do this for a long time. Maybe your issue will trick me into finally doing something about it 😄

**Comment by tarsius** [comment]
Friendly ping!

**Comment by aplaice** [comment]
Thanks for doing this!

**Comment by arnested** [comment]
Sorry it took so long. I think I had a big rewrite of the documentation in mind to go along this. And in the end that just postponed every thought of it. Rediscovered the issues today and decided just to do the easy solution that actually gifts the problem :-)

**Comment by tarsius** [comment]
Thanks!
